In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"D:\Portfolio Project\Restaurant Sales Analysis\01_raw_data\restaurant_sales_raw_data.csv")

In [3]:
data.head()

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
0,ORD_705844,CUST_092,Side Dishes,Side Salad,284.0,1,284.0,12/21/2023,NaN,2023,December,Thursday
1,ORD_338528,CUST_021,Side Dishes,MASHED POTATOES,161.0,3,483.0,5/19/2023,Digital Wallet,2023,May,Friday
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,351.0,4,1404.0,9/27/2023,Credit Card,2023,September,Wednesday
3,ORD_630508,CUST_075,Drinks,Garlic Bread,190.0,2,380.0,8/9/2022,Credit Card,2022,August,Tuesday
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,397.0,4,1588.0,15-05-2022,Cash,2022,May,Sunday

In [4]:
data.tail()

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
100995,ORD_1011964,CUST_12126,Starters,Beef Chili,NaN,3,1491.0,10/29/2023,Credit Card,2023,October,Sunday
100996,ORD_1078725,CUST_78887,Side Dishes,Side Salad,201.0,1,-26.0,7/8/2023,Credit Card,2023,July,Saturday
100997,ORD_1020836,CUST_20998,Drinks,Garlic Bread,247.0,4,988.0,10/18/2023,Digital Wallet,2023,October,Wednesday
100998,ORD_1031161,CUST_31323,Desserts,Fruit Salad,228.0,4,912.0,3/16/2023,Cash,2023,March,Thursday
100999,ORD_160641,CUST_032,Desserts,Garlic Bread,178.0,5,890.0,9/3/2023,Credit Card,2023,September,Sunday

In [5]:
data.shape

(101000, 12)

In [6]:
data.columns

Index(['Order_ID', 'Customer_ID', 'Category', 'Item', 'Price', 'Quantity',
       'Order_Total', 'Order_Date', 'Payment_Method', 'Year', 'Month', 'Day'],
      dtype='object')

In [7]:
data.dtypes

Order_ID           object
Customer_ID        object
Category           object
Item               object
Price             float64
Quantity            int64
Order_Total       float64
Order_Date         object
Payment_Method     object
Year                int64
Month              object
Day                object
dtype: object

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Order_ID        101000 non-null  object
 1   Customer_ID     98979 non-null   object
 2   Category        101000 non-null  object
 3   Item            101000 non-null  object
 4   Price           98989 non-null   float64
 5   Quantity        101000 non-null  int64
 6   Order_Total     101000 non-null  float64
 7   Order_Date      101000 non-null  object
 8   Payment_Method  99014 non-null   object
 9   Year            101000 non-null  int64
 10  Month           101000 non-null  object
 11  Day             101000 non-null  object
dtypes: float64(2), int64(2), object(8)
memory usage: 9.2+ MB

In [9]:
data.describe()

              Price       Quantity    Order_Total           Year
count  98989.000000  101000.000000  101000.000000  101000.000000
mean     294.207821       3.053564     819.790881    2022.491386
std      477.505910       2.720865     769.788302       0.499928
min      -10.000000      -1.000000    -440.000000    2022.000000
25%      177.000000       2.000000     297.000000    2022.000000
50%      235.000000       3.000000     633.000000    2022.000000
75%      309.000000       4.000000    1065.000000    2023.000000
max     9999.000000      50.000000    5995.000000    2023.000000

In [10]:
data.describe(include="object")

,Order_ID,Customer_ID,Category,Item,Order_Date,Payment_Method,Month,Day
count,101000,98979,101000,101000,101000,99014,101000,101000
unique,99502,80890,5,52,1953,10,12,7
top,ORD_1002776,CUST_066,Starters,Garlic Bread,11/25/2023,Credit Card,August,Saturday
freq,3,204,20477,12378,251,30513,9026,14627

In [11]:
data.isnull().sum()

Order_ID             0
Customer_ID       2021
Category             0
Item                 0
Price             2011
Quantity             0
Order_Total          0
Order_Date           0
Payment_Method    1986
Year                 0
Month                0
Day                  0
dtype: int64

In [12]:
(data.isnull().sum()/len(data))*100

Order_ID          0.000000
Customer_ID       2.000990
Category          0.000000
Item              0.000000
Price             1.991089
Quantity          0.000000
Order_Total       0.000000
Order_Date        0.000000
Payment_Method    1.966337
Year              0.000000
Month             0.000000
Day               0.000000
dtype: float64

In [13]:
data.duplicated().sum()

np.int64(1000)

In [14]:
data[data.duplicated()]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
100000,ORD_1026065,CUST_26227,Starters,Cheese Fries,302.0,3,906.0,4/18/2022,Credit Card,2022,April,Monday
100001,ORD_1069683,CUST_69845,Desserts,Chocolate Cake,274.0,4,1096.0,8/2/2023,Credit Card,2023,August,Wednesday
100002,ORD_481478,CUST_044,Drinks,Lemonade,148.0,5,740.0,07/24/2022,Digital Wallet,2022,July,Sunday
100003,ORD_1064337,CUST_64499,Starters,French Fries,229.0,5,1145.0,2/26/2022,Credit Card,2022,February,Saturday
100004,ORD_1077726,CUST_77888,Drinks,Lemonade,98.0,4,392.0,1/16/2022,Digital Wallet,2022,January,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...
100995,ORD_1011964,CUST_12126,Starters,Beef Chili,NaN,3,1491.0,10/29/2023,Credit Card,2023,October,Sunday
100996,ORD_1078725,CUST_78887,Side Dishes,Side Salad,201.0,1,-26.0,7/8/2023,Credit Card,2023,July,Saturday
100997,ORD_1020836,CUST_20998,Drinks,Garlic Bread,247.0,4,988.0,10/18/2023,Digital Wallet,2023,October,Wednesday
100998,ORD_1031161,CUST_31323,Desserts,Fruit Salad,228.0,4,912.0,3/16/2023,Cash,2023,March,Thursday
100999,ORD_160641,CUST_032,Desserts,Garlic Bread,178.0,5,890.0,9/3/2023,Credit Card,2023,September,Sunday

In [15]:
data["Payment_Method"].unique()

array([nan, 'Digital Wallet', 'Credit Card', 'Cash', 'Unknown', 'upi ',
       'cash', 'card', 'Cash ', 'CARD', ' Unknown '], dtype=object)

In [16]:
data["Item"].unique()

array(['Side Salad', ' MASHED POTATOES ', 'Grilled Chicken',
       'Garlic Bread', 'Pasta Alfredo', 'Salmon', 'Vegetarian Platter',
       'Brownie', 'Sweet Potato Fries', 'Mashed Potatoes', 'Lemonade',
       'Orange Juice', 'Chocolate Cake', 'Coca Cola',
       'Grilled Vegetables', 'Cheese Fries', ' CHEESE FRIES ',
       'Beef Chili', 'Chicken Melt', 'Fruit Salad', 'French Fries',
       ' CHICKEN MELT ', 'Ice Cream', 'Cheesecake', ' CHEESECAKE ',
       'Iced Tea', 'Water', ' GRILLED CHICKEN ', 'Nachos Grande',
       ' BEEF CHILI ', 'Onion Rings', ' STEAK ', 'Steak', ' SIDE SALAD ',
       ' PASTA ALFREDO ', ' ICE CREAM ', ' GARLIC BREAD ', ' ICED TEA ',
       ' SWEET POTATO FRIES ', ' COCA COLA ', ' BROWNIE ',
       ' CHOCOLATE CAKE ', ' WATER ', ' LEMONADE ', ' ORANGE JUICE ',
       ' VEGETARIAN PLATTER ', ' FRENCH FRIES ', ' GRILLED VEGETABLES ',
       ' ONION RINGS ', ' FRUIT SALAD ', ' SALMON ', ' NACHOS GRANDE '],
      dtype=object)

In [17]:
data.dtypes

Order_ID           object
Customer_ID        object
Category           object
Item               object
Price             float64
Quantity            int64
Order_Total       float64
Order_Date         object
Payment_Method     object
Year                int64
Month              object
Day                object
dtype: object

In [18]:
data[data["Quantity"]<=0]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
128,ORD_333412,CUST_089,Main Dishes,Pasta Alfredo,367.0,-1,1835.0,1/6/2022,Digital Wallet,2022,January,Thursday
284,ORD_945648,CUST_094,Side Dishes,Side Salad,272.0,0,816.0,8/29/2022,Cash,2022,August,Monday
314,ORD_908926,CUST_084,Desserts,Cheesecake,280.0,0,280.0,8/29/2022,Credit Card,2022,August,Monday
516,ORD_897234,CUST_096,Drinks,Lemonade,107.0,0,107.0,3/23/2023,Cash,2023,March,Thursday
548,ORD_558234,CUST_010,Starters,French Fries,218.0,0,1090.0,12/25/2022,Credit Card,2022,December,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...
100651,ORD_1009374,CUST_9536,Starters,Chicken Melt,297.0,0,1188.0,2/10/2022,Cash,2022,February,Thursday
100707,ORD_1068533,CUST_68695,Desserts,Brownie,196.0,0,623.0,11/25/2023,Cash,2023,November,Saturday
100726,ORD_558234,CUST_010,Starters,French Fries,218.0,0,1090.0,12/25/2022,Credit Card,2022,December,Sunday
100861,ORD_1014104,CUST_14266,Main Dishes,Garlic Bread,243.0,0,243.0,8/7/2022,Unknown,2022,August,Sunday
100975,ORD_1033049,CUST_33211,Side Dishes,Garlic Bread,220.0,0,220.0,1/22/2022,Digital Wallet,2022,January,Saturday

In [19]:
data[data["Quantity"]>20]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
95,ORD_871279,CUST_045,Main Dishes,Pasta Alfredo,444.0,50,2220.0,2/5/2022,Digital Wallet,2022,February,Saturday
677,ORD_286299,CUST_067,Starters,Chicken Melt,336.0,50,336.0,3/31/2022,Credit Card,2022,March,Thursday
1231,ORD_270043,CUST_030,Drinks,Lemonade,99.0,50,198.0,6/12/2023,Credit Card,2023,June,Monday
1912,ORD_563513,CUST_066,Main Dishes,Vegetarian Platter,522.0,50,522.0,11/7/2023,Cash,2023,November,Tuesday
1954,ORD_622006,CUST_051,Starters,Nachos Grande,295.0,50,1475.0,4/2/2023,Credit Card,2023,April,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...
99279,ORD_1081684,CUST_81846,Side Dishes,Garlic Bread,196.0,50,980.0,10/25/2023,Cash,2023,October,Wednesday
99731,ORD_1082136,CUST_82298,Drinks,Water,25.0,50,125.0,10/3/2022,Credit Card,2022,October,Monday
99747,ORD_1082152,CUST_82314,Starters,Garlic Bread,185.0,50,555.0,10/3/2022,Unknown,2022,October,Monday
100364,ORD_601400,CUST_076,Desserts,Brownie,243.0,50,1215.0,11/25/2023,Cash,2023,November,Saturday
100804,ORD_335790,CUST_042,Main Dishes,Pasta Alfredo,342.0,50,342.0,2/24/2022,Cash,2022,February,Thursday

In [20]:
data[data["Price"]<=0]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
392,ORD_892571,CUST_100,Starters,Beef Chili,0.0,4,1672.0,12/20/2022,Digital Wallet,2022,December,Tuesday
889,ORD_848768,CUST_040,Drinks,Water,0.0,2,60.0,12/27/2023,Credit Card,2023,December,Wednesday
1005,ORD_714914,CUST_062,Drinks,Water,0.0,1,38.0,1/14/2023,Digital Wallet,2023,January,Saturday
1008,ORD_317927,CUST_026,Side Dishes,Garlic Bread,0.0,4,792.0,7/23/2022,Digital Wallet,2022,July,Saturday
1276,ORD_724853,CUST_007,Desserts,Chocolate Cake,-10.0,5,1115.0,7/28/2023,Cash,2023,July,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...
98621,ORD_1081026,CUST_81188,Starters,Cheese Fries,-10.0,3,909.0,7/20/2023,Credit Card,2023,July,Thursday
98686,ORD_1081091,NaN,Desserts,Cheesecake,-10.0,3,720.0,10/25/2023,Cash,2023,October,Wednesday
98960,ORD_1081365,CUST_81527,Main Dishes,Grilled Chicken,-10.0,2,1022.0,6/22/2023,Cash,2023,June,Thursday
99479,ORD_1081884,CUST_82046,Desserts,Chocolate Cake,-10.0,4,820.0,2022/07/13,Digital Wallet,2022,July,Wednesday
100145,ORD_1033259,CUST_33421,Main Dishes,Salmon,-10.0,1,703.0,5/1/2023,Digital Wallet,2023,May,Monday

In [21]:
data[data["Price"]>2000]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
239,ORD_215360,CUST_081,Starters,French Fries,9999.0,5,1100.0,1/20/2023,Cash,2023,January,Friday
575,ORD_577955,CUST_084,Side Dishes,Mashed Potatoes,9999.0,4,792.0,12/26/2023,Digital Wallet,2023,December,Tuesday
2146,ORD_123516,CUST_040,Drinks,Coca Cola,9999.0,2,132.0,8/18/2022,Cash,2022,August,Thursday
2171,ORD_903547,CUST_063,Desserts,Garlic Bread,9999.0,5,1325.0,7/8/2023,Cash,2023,July,Saturday
2575,ORD_310503,CUST_075,Drinks,Coca Cola,9999.0,1,73.0,10/20/2023,Cash,2023,October,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...
99774,ORD_1082179,CUST_82341,Side Dishes,Side Salad,9999.0,2,406.0,6/16/2023,Digital Wallet,2023,June,Friday
99985,ORD_1082390,CUST_82552,Side Dishes,Mashed Potatoes,9999.0,3,591.0,2/2/2022,Credit Card,2022,February,Wednesday
100157,ORD_1057694,CUST_57856,Drinks,Orange Juice,9999.0,2,332.0,7/26/2023,NaN,2023,July,Wednesday
100362,ORD_1057217,CUST_57379,Side Dishes,Side Salad,9999.0,1,244.0,17-06-2022,Digital Wallet,2022,June,Friday
100417,ORD_1042732,CUST_42894,Desserts,Ice Cream,9999.0,3,378.0,5/6/2022,Digital Wallet,2022,May,Friday

In [22]:
# Price × Quantity = Order Total
wrong_total = data[
    data["Order_Total"] !=
    data["Price"] * data["Quantity"]
]

wrong_total.head()

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
41,ORD_708630,CUST_081,Main Dishes,Pasta Alfredo,5.0,1,375.0,7/21/2023,Credit Card,2023,July,Friday
95,ORD_871279,CUST_045,Main Dishes,Pasta Alfredo,444.0,50,2220.0,2/5/2022,Digital Wallet,2022,February,Saturday
108,ORD_361022,CUST_068,Drinks,Coca Cola,52.0,5,525.0,11/26/2023,Unknown,2023,November,Sunday
122,ORD_363522,CUST_070,Starters,Garlic Bread,NaN,1,261.0,5/7/2023,Credit Card,2023,May,Sunday
128,ORD_333412,CUST_089,Main Dishes,Pasta Alfredo,367.0,-1,1835.0,1/6/2022,Digital Wallet,2022,January,Thursday

In [23]:
data["Order_Date"] = pd.to_datetime(
    data["Order_Date"],
    errors="coerce"
)

In [24]:
data[data["Order_Date"].isna()]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,397.0,4,1588.0,NaT,Cash,2022,May,Sunday
57,ORD_864219,CUST_040,Side Dishes,Mashed Potatoes,190.0,4,760.0,NaT,Credit Card,2022,March,Friday
68,ORD_514854,CUST_060,Drinks,Orange Juice,124.0,2,248.0,NaT,Credit Card,2023,June,Thursday
131,ORD_467157,CUST_099,Drinks,Garlic Bread,170.0,1,170.0,NaT,Unknown,2023,November,Thursday
159,ORD_118449,CUST_018,Starters,Beef Chili,338.0,5,1690.0,NaT,Credit Card,2022,July,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
100306,ORD_1036057,CUST_36219,Main Dishes,Steak,1041.0,1,1041.0,NaT,Cash,2023,October,Tuesday
100362,ORD_1057217,CUST_57379,Side Dishes,Side Salad,9999.0,1,244.0,NaT,Digital Wallet,2022,June,Friday
100641,ORD_652143,CUST_097,Starters,Chicken Melt,307.0,5,1535.0,NaT,Credit Card,2023,August,Wednesday
100881,ORD_1055417,CUST_55579,Main Dishes,Grilled Chicken,462.0,1,462.0,NaT,Digital Wallet,2023,August,Saturday
100902,ORD_1005949,CUST_6111,Main Dishes,Garlic Bread,222.0,5,1110.0,NaT,Unknown,2023,January,Tuesday

## Cleaning Data

In [25]:
clean_data = data.copy()

In [26]:
clean_data.isnull().sum()

Order_ID             0
Customer_ID       2021
Category             0
Item                 0
Price             2011
Quantity             0
Order_Total          0
Order_Date        1318
Payment_Method    1986
Year                 0
Month                0
Day                  0
dtype: int64

In [27]:
# Handle Missing Customer_ID

In [28]:
clean_data[clean_data["Customer_ID"].isnull()]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
40,ORD_280294,NaN,Desserts,Fruit Salad,199.0,2,398.0,2022-04-13,Digital Wallet,2022,April,Wednesday
91,ORD_104466,NaN,Drinks,Orange Juice,157.0,1,157.0,2022-05-25,Cash,2022,May,Wednesday
161,ORD_857634,NaN,Side Dishes,Garlic Bread,249.0,5,1245.0,2022-06-13,Credit Card,2022,June,Monday
220,ORD_535705,NaN,Drinks,Lemonade,145.0,2,290.0,2022-11-19,Cash,2022,November,Saturday
301,ORD_398973,NaN,Main Dishes,Vegetarian Platter,431.0,5,2155.0,2023-02-18,Digital Wallet,2023,February,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...
100759,ORD_1046911,NaN,Side Dishes,SIDE SALAD,267.0,3,801.0,2022-12-25,Credit Card,2022,December,Sunday
100789,ORD_1045090,NaN,Main Dishes,Garlic Bread,289.0,1,289.0,2022-08-28,Digital Wallet,2022,August,Sunday
100817,ORD_1030471,NaN,Drinks,Iced Tea,88.0,1,88.0,2022-06-11,Digital Wallet,2022,June,Saturday
100841,ORD_1058117,NaN,Starters,Sweet Potato Fries,251.0,1,251.0,2023-05-25,Cash,2023,May,Thursday
100926,ORD_1012665,NaN,Desserts,Fruit Salad,198.0,5,990.0,2022-12-25,Digital Wallet,2022,December,Sunday

In [29]:
clean_data["Customer_ID"] = clean_data["Customer_ID"].fillna("Unknown")

In [30]:
clean_data["Customer_ID"].isnull().sum()

np.int64(0)

In [31]:
# Handle Missing Payment Method

In [32]:
clean_data["Payment_Method"].value_counts(dropna=False)

Payment_Method
Credit Card       30513
Cash              30480
Digital Wallet    30424
Unknown            6091
NaN                1986
Cash                277
CARD                263
 Unknown            254
cash                254
upi                 237
card                221
Name: count, dtype: int64

In [33]:
clean_data["Payment_Method"] = clean_data["Payment_Method"].fillna(
    clean_data["Payment_Method"].mode()[0]
)

In [34]:
clean_data["Payment_Method"].isnull().sum()

np.int64(0)

In [35]:
# Handle Missing Price

In [36]:
clean_data[clean_data["Price"].isnull()]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
122,ORD_363522,CUST_070,Starters,Garlic Bread,NaN,1,261.0,2023-05-07,Credit Card,2023,May,Sunday
152,ORD_232289,CUST_096,Desserts,Brownie,NaN,4,828.0,2022-11-14,Credit Card,2022,November,Monday
165,ORD_869228,CUST_099,Drinks,Water,NaN,3,114.0,2022-12-05,Credit Card,2022,December,Monday
166,ORD_144043,CUST_004,Side Dishes,Side Salad,NaN,4,1148.0,2022-07-22,Digital Wallet,2022,July,Friday
230,ORD_181592,CUST_051,Drinks,Iced Tea,NaN,2,186.0,2022-03-23,Cash,2022,March,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
100875,ORD_1034425,CUST_34587,Main Dishes,Vegetarian Platter,NaN,2,772.0,2023-12-11,Digital Wallet,2023,December,Monday
100899,ORD_1050920,CUST_51082,Desserts,Ice Cream,NaN,2,206.0,2023-02-01,Digital Wallet,2023,February,Wednesday
100918,ORD_1001671,CUST_1833,Drinks,Lemonade,NaN,2,264.0,2022-11-09,Cash,2022,November,Wednesday
100923,ORD_1065266,CUST_65428,Starters,Cheese Fries,NaN,2,604.0,2023-12-21,Credit Card,2023,December,Thursday
100995,ORD_1011964,CUST_12126,Starters,Beef Chili,NaN,3,1491.0,2023-10-29,Credit Card,2023,October,Sunday

In [37]:
clean_data["Price"] = clean_data["Price"].fillna(
    clean_data.groupby("Item")["Price"].transform("median")
)

In [38]:
clean_data["Price"] = clean_data["Price"].fillna(
    clean_data["Price"].median()
)

In [39]:
clean_data["Price"].isnull().sum()

np.int64(0)

In [40]:
clean_data.isnull().sum()

Order_ID             0
Customer_ID          0
Category             0
Item                 0
Price                0
Quantity             0
Order_Total          0
Order_Date        1318
Payment_Method       0
Year                 0
Month                0
Day                  0
dtype: int64

In [41]:
clean_data[clean_data["Order_Date"].isnull()]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,397.0,4,1588.0,NaT,Cash,2022,May,Sunday
57,ORD_864219,CUST_040,Side Dishes,Mashed Potatoes,190.0,4,760.0,NaT,Credit Card,2022,March,Friday
68,ORD_514854,CUST_060,Drinks,Orange Juice,124.0,2,248.0,NaT,Credit Card,2023,June,Thursday
131,ORD_467157,CUST_099,Drinks,Garlic Bread,170.0,1,170.0,NaT,Unknown,2023,November,Thursday
159,ORD_118449,CUST_018,Starters,Beef Chili,338.0,5,1690.0,NaT,Credit Card,2022,July,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
100306,ORD_1036057,CUST_36219,Main Dishes,Steak,1041.0,1,1041.0,NaT,Cash,2023,October,Tuesday
100362,ORD_1057217,CUST_57379,Side Dishes,Side Salad,9999.0,1,244.0,NaT,Digital Wallet,2022,June,Friday
100641,ORD_652143,CUST_097,Starters,Chicken Melt,307.0,5,1535.0,NaT,Credit Card,2023,August,Wednesday
100881,ORD_1055417,CUST_55579,Main Dishes,Grilled Chicken,462.0,1,462.0,NaT,Digital Wallet,2023,August,Saturday
100902,ORD_1005949,CUST_6111,Main Dishes,Garlic Bread,222.0,5,1110.0,NaT,Unknown,2023,January,Tuesday

In [42]:
data.loc[clean_data["Order_Date"].isna(), "Order_Date"].head(20)

4      NaT
57     NaT
68     NaT
131    NaT
159    NaT
769    NaT
793    NaT
797    NaT
895    NaT
952    NaT
969    NaT
1045   NaT
1082   NaT
1126   NaT
1200   NaT
1274   NaT
1304   NaT
1356   NaT
1382   NaT
1435   NaT
Name: Order_Date, dtype: datetime64[ns]

In [43]:
clean_data["Order_Date"] = pd.to_datetime(
    clean_data["Order_Date"],
    errors="coerce",
    dayfirst=False
)

In [44]:
clean_data["Order_Date"].isnull().sum()

np.int64(1318)

In [45]:
data.dtypes

Order_ID                  object
Customer_ID               object
Category                  object
Item                      object
Price                    float64
Quantity                   int64
Order_Total              float64
Order_Date        datetime64[ns]
Payment_Method            object
Year                       int64
Month                     object
Day                       object
dtype: object

In [46]:
median_date = clean_data["Order_Date"].dropna().median()

clean_data["Order_Date"] = clean_data["Order_Date"].fillna(median_date)

In [47]:
clean_data["Order_Date"].isnull().sum()

np.int64(0)

In [48]:
clean_data.duplicated().sum()

np.int64(1000)

In [49]:
clean_data = clean_data.drop_duplicates()

In [50]:
clean_data.duplicated().sum()

np.int64(0)

In [51]:
clean_data.shape

(100000, 12)

In [52]:
data.head()

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
0,ORD_705844,CUST_092,Side Dishes,Side Salad,284.0,1,284.0,2023-12-21,NaN,2023,December,Thursday
1,ORD_338528,CUST_021,Side Dishes,MASHED POTATOES,161.0,3,483.0,2023-05-19,Digital Wallet,2023,May,Friday
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,351.0,4,1404.0,2023-09-27,Credit Card,2023,September,Wednesday
3,ORD_630508,CUST_075,Drinks,Garlic Bread,190.0,2,380.0,2022-08-09,Credit Card,2022,August,Tuesday
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,397.0,4,1588.0,NaT,Cash,2022,May,Sunday

In [53]:
clean_data.select_dtypes(include="object").columns

Index(['Order_ID', 'Customer_ID', 'Category', 'Item', 'Payment_Method',
       'Month', 'Day'],
      dtype='object')

In [54]:
text_cols = clean_data.select_dtypes(include="object").columns

for col in text_cols:
    clean_data[col] = clean_data[col].str.strip()

In [55]:
data.head()

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
0,ORD_705844,CUST_092,Side Dishes,Side Salad,284.0,1,284.0,2023-12-21,NaN,2023,December,Thursday
1,ORD_338528,CUST_021,Side Dishes,MASHED POTATOES,161.0,3,483.0,2023-05-19,Digital Wallet,2023,May,Friday
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,351.0,4,1404.0,2023-09-27,Credit Card,2023,September,Wednesday
3,ORD_630508,CUST_075,Drinks,Garlic Bread,190.0,2,380.0,2022-08-09,Credit Card,2022,August,Tuesday
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,397.0,4,1588.0,NaT,Cash,2022,May,Sunday

In [56]:
clean_data["Payment_Method"].unique()

array(['Credit Card', 'Digital Wallet', 'Cash', 'Unknown', 'upi', 'cash',
       'card', 'CARD'], dtype=object)

In [57]:
clean_data["Payment_Method"].value_counts()

Payment_Method
Credit Card       32176
Cash              30444
Digital Wallet    30129
Unknown            6280
CARD                262
cash                253
upi                 237
card                219
Name: count, dtype: int64

In [58]:
clean_data["Payment_Method"] = clean_data["Payment_Method"].replace({
    "CARD": "Credit Card",
    "card": "Credit Card",
    "cash": "Cash",
    "upi": "Digital Wallet"
})

In [59]:
clean_data["Payment_Method"].value_counts()

Payment_Method
Credit Card       32657
Cash              30697
Digital Wallet    30366
Unknown            6280
Name: count, dtype: int64

In [60]:
clean_data["Payment_Method"] = clean_data["Payment_Method"].replace(
    "Unknown",
    np.nan
)

## Checking Outliers

In [61]:
clean_data[clean_data["Price"] <= 0]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
392,ORD_892571,CUST_100,Starters,Beef Chili,0.0,4,1672.0,2022-12-20,Digital Wallet,2022,December,Tuesday
889,ORD_848768,CUST_040,Drinks,Water,0.0,2,60.0,2023-12-27,Credit Card,2023,December,Wednesday
1005,ORD_714914,CUST_062,Drinks,Water,0.0,1,38.0,2023-01-14,Digital Wallet,2023,January,Saturday
1008,ORD_317927,CUST_026,Side Dishes,Garlic Bread,0.0,4,792.0,2022-07-23,Digital Wallet,2022,July,Saturday
1276,ORD_724853,CUST_007,Desserts,Chocolate Cake,-10.0,5,1115.0,2023-07-28,Cash,2023,July,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...
98583,ORD_1080988,CUST_81150,Main Dishes,Vegetarian Platter,0.0,1,539.0,2022-03-08,Cash,2022,March,Tuesday
98621,ORD_1081026,CUST_81188,Starters,Cheese Fries,-10.0,3,909.0,2023-07-20,Credit Card,2023,July,Thursday
98686,ORD_1081091,Unknown,Desserts,Cheesecake,-10.0,3,720.0,2023-10-25,Cash,2023,October,Wednesday
98960,ORD_1081365,CUST_81527,Main Dishes,Grilled Chicken,-10.0,2,1022.0,2023-06-22,Cash,2023,June,Thursday
99479,ORD_1081884,CUST_82046,Desserts,Chocolate Cake,-10.0,4,820.0,2022-12-25,Digital Wallet,2022,July,Wednesday

In [62]:
clean_data[clean_data["Price"] > 1500]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
239,ORD_215360,CUST_081,Starters,French Fries,9999.0,5,1100.0,2023-01-20,Cash,2023,January,Friday
575,ORD_577955,CUST_084,Side Dishes,Mashed Potatoes,9999.0,4,792.0,2023-12-26,Digital Wallet,2023,December,Tuesday
2146,ORD_123516,CUST_040,Drinks,Coca Cola,9999.0,2,132.0,2022-08-18,Cash,2022,August,Thursday
2171,ORD_903547,CUST_063,Desserts,Garlic Bread,9999.0,5,1325.0,2023-07-08,Cash,2023,July,Saturday
2575,ORD_310503,CUST_075,Drinks,Coca Cola,9999.0,1,73.0,2023-10-20,Cash,2023,October,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...
97651,ORD_1080056,CUST_80218,Side Dishes,Side Salad,9999.0,5,1340.0,2022-03-17,Credit Card,2022,March,Thursday
98895,ORD_1081300,CUST_81462,Drinks,Orange Juice,9999.0,3,588.0,2023-11-25,Credit Card,2023,November,Saturday
99454,ORD_1081859,CUST_82021,Drinks,Orange Juice,9999.0,5,905.0,2023-03-19,Cash,2023,March,Sunday
99774,ORD_1082179,CUST_82341,Side Dishes,Side Salad,9999.0,2,406.0,2023-06-16,Digital Wallet,2023,June,Friday
99985,ORD_1082390,CUST_82552,Side Dishes,Mashed Potatoes,9999.0,3,591.0,2022-02-02,Credit Card,2022,February,Wednesday

In [63]:
len(clean_data[clean_data["Price"] <= 0])

387

In [64]:
len(clean_data[clean_data["Price"] > 1500])

195

In [65]:
clean_data.loc[
    clean_data["Price"] <= 0,
    "Price"
] = np.nan

In [66]:
clean_data.loc[
    clean_data["Price"] > 1500,
    "Price"
] = np.nan

In [67]:
clean_data["Price"] = clean_data["Price"].fillna(
    clean_data.groupby("Item")["Price"].transform("median")
)

In [68]:
clean_data[clean_data["Quantity"] <= 0]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
128,ORD_333412,CUST_089,Main Dishes,Pasta Alfredo,367.0,-1,1835.0,2022-01-06,Digital Wallet,2022,January,Thursday
284,ORD_945648,CUST_094,Side Dishes,Side Salad,272.0,0,816.0,2022-08-29,Cash,2022,August,Monday
314,ORD_908926,CUST_084,Desserts,Cheesecake,280.0,0,280.0,2022-08-29,Credit Card,2022,August,Monday
516,ORD_897234,CUST_096,Drinks,Lemonade,107.0,0,107.0,2023-03-23,Cash,2023,March,Thursday
548,ORD_558234,CUST_010,Starters,French Fries,218.0,0,1090.0,2022-12-25,Credit Card,2022,December,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...
98418,ORD_1080823,CUST_80985,Main Dishes,Vegetarian Platter,521.0,-1,2084.0,2022-04-27,Credit Card,2022,April,Wednesday
98420,ORD_1080825,CUST_80987,Main Dishes,Vegetarian Platter,409.0,-1,2045.0,2022-02-04,Credit Card,2022,February,Friday
98453,ORD_1015834,CUST_81020,Main Dishes,PASTA ALFREDO,380.0,-1,1508.0,2022-07-23,Digital Wallet,2022,July,Saturday
98968,ORD_1081373,CUST_81535,Side Dishes,Garlic Bread,220.0,-1,1100.0,2022-10-30,Credit Card,2022,October,Sunday
99207,ORD_1081612,CUST_81774,Side Dishes,Mashed Potatoes,203.0,0,812.0,2023-01-17,Cash,2023,January,Tuesday

In [69]:
clean_data[clean_data["Quantity"] > 20]

,Order_ID,Customer_ID,Category,Item,Price,Quantity,Order_Total,Order_Date,Payment_Method,Year,Month,Day
95,ORD_871279,CUST_045,Main Dishes,Pasta Alfredo,444.0,50,2220.0,2022-02-05,Digital Wallet,2022,February,Saturday
677,ORD_286299,CUST_067,Starters,Chicken Melt,336.0,50,336.0,2022-03-31,Credit Card,2022,March,Thursday
1231,ORD_270043,CUST_030,Drinks,Lemonade,99.0,50,198.0,2023-06-12,Credit Card,2023,June,Monday
1912,ORD_563513,CUST_066,Main Dishes,Vegetarian Platter,522.0,50,522.0,2023-11-07,Cash,2023,November,Tuesday
1954,ORD_622006,CUST_051,Starters,Nachos Grande,295.0,50,1475.0,2023-04-02,Credit Card,2023,April,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...
98051,ORD_1080456,CUST_80618,Main Dishes,Salmon,920.0,50,3680.0,2023-12-19,Digital Wallet,2023,December,Tuesday
98528,ORD_1080933,CUST_81095,Desserts,Cheesecake,246.0,50,246.0,2023-08-16,Credit Card,2023,August,Wednesday
99279,ORD_1081684,CUST_81846,Side Dishes,Garlic Bread,196.0,50,980.0,2023-10-25,Cash,2023,October,Wednesday
99731,ORD_1082136,CUST_82298,Drinks,Water,25.0,50,125.0,2022-10-03,Credit Card,2022,October,Monday
99747,ORD_1082152,CUST_82314,Starters,Garlic Bread,185.0,50,555.0,2022-10-03,NaN,2022,October,Monday

In [70]:
clean_data.loc[
    clean_data["Quantity"] <= 0,
    "Quantity"
] = 1

In [71]:
clean_data.loc[
    clean_data["Quantity"] > 20,
    "Quantity"
] = 5

In [72]:
clean_data["Order_Total"] = (
    clean_data["Price"] *
    clean_data["Quantity"]
)

In [78]:
clean_data["Item"].unique()

array(['Side Salad', 'MASHED POTATOES', 'Grilled Chicken', 'Garlic Bread',
       'Pasta Alfredo', 'Salmon', 'Vegetarian Platter', 'Brownie',
       'Sweet Potato Fries', 'Mashed Potatoes', 'Lemonade',
       'Orange Juice', 'Chocolate Cake', 'Coca Cola',
       'Grilled Vegetables', 'Cheese Fries', 'CHEESE FRIES', 'Beef Chili',
       'Chicken Melt', 'Fruit Salad', 'French Fries', 'CHICKEN MELT',
       'Ice Cream', 'Cheesecake', 'CHEESECAKE', 'Iced Tea', 'Water',
       'GRILLED CHICKEN', 'Nachos Grande', 'BEEF CHILI', 'Onion Rings',
       'STEAK', 'Steak', 'SIDE SALAD', 'PASTA ALFREDO', 'ICE CREAM',
       'GARLIC BREAD', 'ICED TEA', 'SWEET POTATO FRIES', 'COCA COLA',
       'BROWNIE', 'CHOCOLATE CAKE', 'WATER', 'LEMONADE', 'ORANGE JUICE',
       'VEGETARIAN PLATTER', 'FRENCH FRIES', 'GRILLED VEGETABLES',
       'ONION RINGS', 'FRUIT SALAD', 'SALMON', 'NACHOS GRANDE'],
      dtype=object)

In [79]:
clean_data["Item"] = (clean_data["Item"].astype(str).str.strip().str.title())

In [80]:
clean_data["Item"].unique()

array(['Side Salad', 'Mashed Potatoes', 'Grilled Chicken', 'Garlic Bread',
       'Pasta Alfredo', 'Salmon', 'Vegetarian Platter', 'Brownie',
       'Sweet Potato Fries', 'Lemonade', 'Orange Juice', 'Chocolate Cake',
       'Coca Cola', 'Grilled Vegetables', 'Cheese Fries', 'Beef Chili',
       'Chicken Melt', 'Fruit Salad', 'French Fries', 'Ice Cream',
       'Cheesecake', 'Iced Tea', 'Water', 'Nachos Grande', 'Onion Rings',
       'Steak'], dtype=object)

In [81]:
clean_data["Category"] = (clean_data["Category"].astype(str).str.strip().str.title())

In [82]:
clean_data["Category"].unique()

array(['Side Dishes', 'Main Dishes', 'Drinks', 'Desserts', 'Starters'],
      dtype=object)

## Final Validation

In [73]:
clean_data.isnull().sum()

Order_ID             0
Customer_ID          0
Category             0
Item                 0
Price                0
Quantity             0
Order_Total          0
Order_Date           0
Payment_Method    6280
Year                 0
Month                0
Day                  0
dtype: int64

In [74]:
clean_data.duplicated().sum()

np.int64(0)

In [75]:
clean_data.describe()

,Price,Quantity,Order_Total,Order_Date,Year
count,100000.000000,100000.000000,100000.000000,100000,100000.00000
mean,275.724123,2.951800,816.594223,2022-12-28 17:48:04.608000256,2022.49150
min,5.000000,1.000000,5.000000,2022-01-01 00:00:00,2022.00000
25%,178.000000,2.000000,293.000000,2022-07-02 00:00:00,2022.00000
50%,235.000000,3.000000,630.000000,2022-12-25 00:00:00,2022.00000
75%,309.000000,4.000000,1060.000000,2023-06-26 00:00:00,2023.00000
max,1199.000000,5.000000,5995.000000,2023-12-31 00:00:00,2023.00000
std,197.472645,1.434969,768.978925,NaN,0.49993

In [76]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Order_ID        100000 non-null  object
 1   Customer_ID     100000 non-null  object
 2   Category        100000 non-null  object
 3   Item            100000 non-null  object
 4   Price           100000 non-null  float64
 5   Quantity        100000 non-null  int64
 6   Order_Total     100000 non-null  float64
 7   Order_Date      100000 non-null  datetime64[ns]
 8   Payment_Method  93720 non-null   object
 9   Year            100000 non-null  int64
 10  Month           100000 non-null  object
 11  Day             100000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(7)
memory usage: 9.9+ MB

In [83]:
clean_data.to_csv(r"D:\Portfolio Project\Restaurant Sales Analysis\02_cleaned_data\restaurant_sales_cleaned_data.csv",index=False)